/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex('products').del();
	await knex('products').insert([
		{
			id: 1,
			name: 'Basketball',
			price: 12.99,
			category: 'Sports',
			type: 'ball',
			rating: 5,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 2,
			name: 'Baseball',
			price: 9.99,
			category: 'Sports',
			type: 'ball',
			rating: 4,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 3,
			name: 'Tennis Racquet',
			price: 89.99,
			category: 'Sports',
			type: 'racquet',
			rating: 3,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 4,
			name: 'Running Shoes',
			price: 109.99,
			category: 'Sports',
			type: 'shoes',
			rating: 4,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 5,
			name: 'Wrestling Shoes',
			price: 79.99,
			category: 'Sports',
			type: 'shoes',
			rating: 3,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 6,
			name: 'Soccer Ball',
			price: 10.99,
			category: 'Sports',
			type: 'ball',
			rating: 5,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 7,
			name: 'Soccer Cleats',
			price: 79.99,
			category: 'Sports',
			type: 'shoes',
			rating: 4,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 8,
			name: 'T-Shirt',
			price: 12.99,
			category: 'Fashion',
			type: 'shirt',
			rating: 5,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 9,
			name: 'Jeans',
			price: 9.99,
			category: 'Fashion',
			type: 'pants',
			rating: 4,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 10,
			name: 'Socks',
			price: 89.99,
			category: 'Fashion',
			type: 'socks',
			rating: 3,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 11,
			name: 'Shoes',
			price: 109.99,
			category: 'Fashion',
			type: 'shoes',
			rating: 4,
			isPublished: true,
			createdAt: new Date(),
		},
		{
			id: 12,
			name: 'Hat',
			price: 79.99,
			category: 'Fashion',
			type: 'hat',
			rating: 3,
			isPublished: true,
			createdAt: new Date(),
		},
	]);
};
